name: My first Workflow
on: [push,fork]
jobs:
    firstjobs: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2
            - name: List and Read File
              run: |
                echo "My First github actions job"
                ls -la
                cat README.md
            - name: Generate a ASCII artwork
              run: cowsay -f dragon "Run for cover, I am a dragon... RAWR" >> dragon.txt
            # - name: List the Files
            #   run: ls
            # - name: Read the File
            #   run: cat README.md