name: My first Workflow
on: [push,fork]
jobs:
    firstjobs: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2
            - name: Welecome message
              run: echo "My First github actions job"
            - name: List the Files
              run: ls
            - name: Read the File
              run: cat README.md