name: Installing library example workflow
on: [push]
jobs:
    secondjobs: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2

            - name: make script executable
              run: sudo chmod +x ascii-script.sh

            - name: Executing shell script
              run: ./ascii-script.sh

            # - name: Install cowsay library
            #   run: sudo apt-get install cowsay -y

            # - name: Generate a ASCII artwork
            #   run: cowsay -f dragon "Run for cover, I am a dragon... RAWR" >> dragon.txt

            # - name: Test File Exists
            #   run: grep -i "dragon" dragon.txt
            
            # - name: Read File
            #   run: cat dragon.txt
            
            # - name: List Repo files
            #   run: ls -ltra