name: Multi Job Example
on: [push]
jobs:
    dependency_install_job:
        runs-on: ubuntu-latest
        steps:
          - name: Install cowsay
            run: sudo apt-get install cowsay -y
          - name: Execute Cowsay cmd
            run: cowsay -f elephant "i am elephant ba..." >> /tmp/elephant.txt
          - name: Sleep for 30 seconds
            run: sleep 30
          - name: Upload a artifact
            uses: actions/upload-artifact@v4.6.2
            with:
              name: elephant-file
              path: /tmp/elephant.txt
    test_job:
        runs-on: ubuntu-latest
        needs: [dependency_install_job]
        steps:
            - uses: actions/download-artifact@v4.3.0
              name: Download elephant text file from first job
              with:
                name: elephant-file
                path: /tmp/elephant.txt
            
            - name: Test File Exists
              run: grep -iR "elephant" /tmp/elephant.txt

    Deploy_job:
        runs-on: ubuntu-latest
        needs: [test_job]
        steps:
          - uses: actions/download-artifact@v4.3.0
            name: Download elephant text file from first job
            with:
              name: elephant-file
              path: /tmp/elephant.txt

          - name: List Files
            run: |
                cd /tmp
                ls -la
        #   - name: Read File
        #     run: cat /tmp/elephant.txt
            
        