name: Variables And Secrets 
on: workflow_dispatch # this to run workflow manually from console
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx # environment variables declared at workflow/job level
jobs:
    variables_and_secrests:
        runs-on: ubuntu-latest
        steps:
          - name: Docker build
            run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest

          - name: Docker Login
            run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

          - name: Docker publish
            run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          
    deploy:
      runs-on: ubuntu-latest
      needs: variables_and_secrests
      steps:
        - name: Docker run
          run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest